# CSV File

In [ ]:
import csv
with open("data.csv","w",newline="")as file:
    writer = csv.writer(file)
    writer.writerow(["Name","Age","City"])
    writer.writerow(["Anitha","20","Uppada"])
    writer.writerow(["Suji","20","Uppada"])

# Library Numpy

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
print(a)
print(type(a))


[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
l=range(1000)
%timeit [i**2 for i in l]

95.8 μs ± 3.17 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [8]:
a=np.arange(1000)
%timeit a**2


1.82 μs ± 28.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# CREATING ARRAYS


In [9]:
a=np.array([1,2,3,4])
print(a.ndim)


1


In [13]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [15]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
print(a.shape)

(4,)


In [19]:
print(b.shape)


(2, 3)


In [18]:
print(c.shape)

(2, 2, 2)


# FUNCTIONS FOR CREATING ARRAY


In [20]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [27]:
a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [28]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
a=np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
a=np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [33]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [35]:
print(np.diag(a))

[1 2 3 4]


# BASIC DATATYPES

In [37]:
a=np.arange(10)
print(a.dtype)

int64


In [38]:
a=np.arange(10,dtype="float64")
print(a.dtype)

float64


In [42]:
a=np.zeros((3,3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


# OTHER DATATPYES


In [45]:
a=np.array([1+2j,2+4j])
print(a.dtype)

complex128


In [47]:
a=np.array([True,False])
print(a.dtype)

bool


In [49]:
a=np.array(['ANITHA','SUJI'])
print(a.dtype)

<U6


 # INDEXING AND SLICING

In [52]:
a=np.arange(10)
print(a[5])

5


In [56]:
a=np.diag([1,2,3])
print(a[2,2])


3


In [57]:
a=np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


# Slicing

In [2]:
import numpy as np
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(a[1:8:4])

[1 5]


In [4]:
a=np.diag([1,2,3])
print(a[2,2])

3


In [5]:
a[2,1]=5
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [6]:
a=np.arange(15)
a[5:]=7
a

array([0, 1, 2, 3, 4, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

#  Copies and Viewing

In [7]:
a=np.arange(10)
b=a[::2]
print(a)
print(b)



[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [8]:
print(np.shares_memory(a,b))

True


In [9]:
b[0]=10
print(b)
print(a)

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [10]:
a=np.arange(10)
b=a[::2].copy()
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [11]:
b[0]=10
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


# Random number Generation

In [12]:
a=np.random.randint(0,25,15)
print(a)

[20  2 16 17 14 24 10 21 24  2  3 16 20 10 16]


In [13]:
mask=(a%2==0)

In [14]:
a[mask]=-1
print(a)

[-1 -1 -1 17 -1 -1 -1 21 -1 -1  3 -1 -1 -1 -1]


# Element Wise Operations

# 1 Basic Operations

In [16]:
a=np.array([1,2,3,4])
print(a+1)

[2 3 4 5]


In [17]:
print(a**2)

[ 1  4  9 16]


# All Arthmetic Operations Element Wise

In [18]:
b=np.ones(4) +1
print("a=",a)
print("b=",b)

a= [1 2 3 4]
b= [2. 2. 2. 2.]


In [19]:
print(a*b)

[2. 4. 6. 8.]


In [21]:
c=np.diag([1,2,3,4])
print(c)
print(c*c)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [22]:
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


# Comparision Operator

In [23]:
a=np.array([1,2,3,4])
b=np.array([5,2,7,3])
print(a==b)

[False  True False False]


In [24]:
print(a>b)

[False False False  True]


In [25]:
print(a<b)

[ True False  True False]


In [26]:
# array wise comparision

a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([1,2,3,4])
print(np.array_equal(a,c))
print(np.array_equal(a,b))

True
False


# Logical Operator

In [27]:
a=np.array([1,0,1,0],dtype="bool")
b=np.array([1,1,0,0],dtype="bool")


In [28]:
print(np.logical_or(a,b))

[ True  True  True False]


In [29]:
print(np.logical_and(a,b))

[ True False False False]


In [30]:
print(np.logical_not(a,b))

[False  True False  True]


# Trignomentry Transactional Function

In [31]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [32]:
print(np.sin(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [33]:
np.log(a)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_9556\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [34]:
a="Aditya Degree College"
print(a[::-1])

egelloC eergeD aytidA


In [35]:
b=a.replace("e","r")
print(b)

Aditya Drgrrr Collrgr


In [36]:
a="Aditya Degree College"
b=""
for i in a:
    if i=="e":
        b+="r"
    else:
        b+=i
print(b)
    

Aditya Drgrrr Collrgr


In [37]:
b=a.split(",")
print(b)

['Aditya Degree College']


In [39]:
a="   Anu"
b=a.strip()
print(b)

Anu
